# Generated by Django 6.0.1 on 2026-02-03 16:21

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('EBK_ORGANIZED', 'EBK Organized Activities'), ('PARTICIPATION', 'Participation (Mentoring, Committees)'), ('PRESENTATION', 'Presentations'), ('KNOWLEDGE_CONTRIBUTION', 'Contributions to Knowledge'), ('WORK_BASED', 'Work-Based Activities'), ('INFORMAL', 'Informal (Self-Study, Conferences)'), ('ACCREDITED_PROVIDER', 'Accredited Service Provider')], max_length=50)),
                ('date_completed', models.DateField()),
                ('hours_spent', models.PositiveIntegerField(help_text='Total hours spent')),
                ('supporting_document', cloudinary.models.CloudinaryField(blank=True, help_text='Upload certificate or proof of attendance', max_length=255, null=True, verbose_name='document')),
                ('pdu_units_awarded', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CPD Activity',
                'verbose_name_plural': 'CPD Activities',
                'ordering': ['-date_completed'],
            },
        ),
    ]
