# Generated by Django 6.0.1 on 2026-02-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_engineering_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='firebasese_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
