# Generated by Django 6.0.1 on 2026-02-04 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_engineer_firebasese_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='firebasese_uid',
            new_name='firebase_uid',
        ),
        migrations.AlterField(
            model_name='engineer',
            name='ebk_registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='EBK registration number must be alphanumeric and uppercase.', regex='^EBK\\/[0-9]{4}\\/[0-9]{4,6}$')]),
        ),
    ]
